/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:aa2fcfae-3c35-4764-b307-58282fbbaf5d",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_uvJXNRkXj",
    "aws_user_pools_web_client_id": "6e76hs6ts0be0nt4f8o1mqn3ss",
    "oauth": {
        "domain": "habitbuilder4a259251-4a259251-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://habit-builder-2.herokuapp.com/,http://localhost:3000/",
        "redirectSignOut": "https://habit-builder-2.herokuapp.com/,http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
