/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:9484a4d3-b06b-4838-a4d2-559e63b1c3aa",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_sPGpdKAXI",
    "aws_user_pools_web_client_id": "22n42mlio5sfcu2fakhn5320b4",
    "oauth": {
        "domain": "habitbuilderd2e59baf-d2e59baf-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://habit-builder-2.herokuapp.com/",
        "redirectSignOut": "https://habit-builder-2.herokuapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
